### ISSUE TITLE
Upgrade testcontainers dependency to 0.15

### ISSUE THREAD

**Issue by meistermeier** [knutwalker/neo4j-testcontainers-rs#17]
Haven't checked yet, but I think that this includes API changes.
After we have done this, we could discuss with testcontainers/atomicjar about the shared repository for rust implementations again.

**Comment by knutwalker** [comment]
[Changelog](https://github.com/testcontainers/testcontainers-rs/blob/0.15/CHANGELOG.md#0150---2023-09-28) looks fine. We actually hadn't used `Cli::new` anywhere, only `Cli::default`, so we're not hit by the removal of podman support 😅
