### ISSUE TITLE
Enterprise edition

### ISSUE THREAD

**Issue by Reichenbachian** [knutwalker/neo4j-testcontainers-rs#20]
Was it intentional to take out all the enterprise code in your last commit? Looks like it could be accidental.

**Comment by knutwalker** [comment]
I added this module to the community modules from testcontainers and while doing so, we decided to not include the option for enabling the enterprise edition.
I left this crate as a small wrapper around the community module, but I can also add the EE back in.

**Comment by knutwalker** [comment]
I released 0.3.0 where you can set the enterprise edition. The API looks a bit different than before since it's still build on top of the community module, you can see an [example in the readme](https://github.com/knutwalker/neo4j-testcontainers-rs?tab=readme-ov-file#enterprise-edition)
